# Generated by Django 5.0.7 on 2024-08-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('consultant', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
    ]
