# Generated by Django 5.0.7 on 2024-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
