# Generated by Django 5.0.7 on 2024-08-14 09:41

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='due_date',
            new_name='request_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='supply_date',
            field=models.DateField(default=datetime.date.today().isoformat()),
            preserve_default=False,
        ),
    ]