# Generated by Django 5.0.7 on 2024-08-14 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_due_date_order_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
