# Generated by Django 5.0.7 on 2024-08-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_requester_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requester_username',
            field=models.CharField(max_length=255),
        ),
    ]
