# Generated by Django 5.0.7 on 2024-08-07 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('supply_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('lpo_no', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=50)),
                ('project_location', models.CharField(max_length=100)),
                ('project_consultant', models.CharField(max_length=100)),
                ('project_stage', models.CharField(max_length=50)),
                ('requester_signature', models.CharField(max_length=50)),
                ('supplier_signature', models.CharField(max_length=50)),
                ('store_keeper_signature', models.CharField(max_length=50)),
                ('other_signature', models.CharField(max_length=50)),
                ('requester_date', models.DateTimeField()),
                ('supplier_date', models.DateField()),
                ('store_keeper_date', models.DateField()),
                ('others_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('material_request_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='material_request_pics')),
                ('qty', models.IntegerField()),
                ('item_unit', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='material_request.materialrequest')),
            ],
        ),
    ]
